version: "3.9"

services:
  spark-master:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-master
    # command: ["/opt/spark/sbin/start-master.sh", "--foreground"]
    # command: ["/opt/spark/sbin/start-master.sh", "--host", "0.0.0.0"]
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "--host", "0.0.0.0"]
    volumes:
      - ./spark:/opt/scripts 
      #- ./jars:/opt/spark/jars
      #- ./spark_conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - spark_net

  spark-worker:
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: spark-worker
    # command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "--host", "0.0.0.0", "spark://spark-master:7077"]
    volumes:
      - ./scripts:/opt/scripts # kafka cp 하기 위해 추가
      #- ./jars:/opt/spark/jars
      #- ./spark_conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf

    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - spark_net
  
  airflow-init:
    image: apache/airflow:2.6.2
    container_name: airflow-init
    entrypoint: /bin/bash
    command: -c "
      airflow db init &&
      airflow users create \
        --username airflow \
        --password airflow \
        --firstname admin \
        --lastname user \
        --role Admin \
        --email admin@example.com
      "
    environment:
      - AIRFLOW__CORE__FERNET_KEY=4XvY8cOq0A9qGp-6V9r9uJAVDPDTgb_26RhiJ9c9zkQ=
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
    depends_on:
      - airflow-postgres
    networks:
      - spark_net

  pyspark:
    build:
      context: ./pyspark
      dockerfile: Dockerfile
    container_name: pyspark-notebook
    user: "root"
    environment:
      - NB_GID=100
      - GRANT_SUDO=yes
        # Spark 환경 변수 추가
      - SPARK_HOME=/opt/spark
      - PATH=/opt/spark/bin:/opt/spark/sbin:$PATH
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=lab
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
      - "4042:4040"
    networks:
      - spark_net
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='' --ip=0.0.0.0

  
  airflow-webserver:
    image: apache/airflow:2.6.2
    command: webserver
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
      - airflow-postgres
      - airflow-redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__FERNET_KEY=4XvY8cOq0A9qGp-6V9r9uJAVDPDTgb_26RhiJ9c9zkQ=
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
      - AIRFLOW_UID=50000
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - spark_net

  airflow-scheduler:
    image: apache/airflow:2.6.2
    command: scheduler
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-postgres
      - airflow-redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__FERNET_KEY=4XvY8cOq0A9qGp-6V9r9uJAVDPDTgb_26RhiJ9c9zkQ=
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW_UID=50000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - spark_net

  airflow-postgres:
    image: postgres:15
    container_name: airflow-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-postgres-db:/var/lib/postgresql/data
    networks:
      - spark_net

  airflow-redis:
    image: redis:7
    container_name: airflow-redis
    restart: always
    networks:
      - spark_net
    
  airflow-worker:
    image: apache/airflow:2.6.2
    command: celery worker
    container_name: airflow-worker
    restart: always
    depends_on:
      - airflow-postgres
      - airflow-redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__FERNET_KEY=4XvY8cOq0A9qGp-6V9r9uJAVDPDTgb_26RhiJ9c9zkQ=
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@airflow-postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://airflow-redis:6379/0
      - AIRFLOW_UID=50000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    networks:
      - spark_net

  kafka:
    image: bitnami/kafka:3.4
    container_name: kafka
    # Kafka 데이터를 로컬에 유지하도록 볼륨 연결
    volumes:
      - ./kafka-persistence:/bitnami/kafka
      - ./scripts:/opt/scripts
    environment:
      # KRaft 모드에서 노드 식별용 ID
      - KAFKA_CFG_NODE_ID=1
      # Kafka 역할: broker와 controller를 동시에 수행
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      # 브로커와 컨트롤러 리스너 설정
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      # 클라이언트에게 알려줄 브로커 주소 (컨트롤러 제외), plain text는 나중에 ssl 등으로 바꿔야함
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      # KRaft 컨트롤러 관련 설정
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # 편의 설정
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    # 브로커 클라이언트 포트와 내부 컨트롤러 포트
    ports:
      - "9092:9092"  # Kafka 클라이언트 접속용
      - "9093:9093"  # KRaft 컨트롤러 내부 통신용
    networks:
      - spark_net
      
  cassandra:
    image: bitnami/cassandra:4.0.11
    container_name: cassandra
    volumes:
      - ./cassandra-persistence:/bitnami
    environment:
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
    ports:
      - "9042:9042"
    networks:
      - spark_net

  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
    ports:
      - "8181:8181"
    depends_on:
      - minio
    networks:
      - spark_net

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      spark_net:
        aliases:
          - warehouse.minio
    volumes:
      - ./minio-data:/data

  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "
    networks:
      - spark_net

  kafka-cli:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-cli
    depends_on:
      - kafka
    entrypoint: ["sleep", "infinity"]
    networks:
      - spark_net

volumes:
  airflow-postgres-db:

networks:
  spark_net:
    driver: bridge
